[package]
name = "aeroplane-chess"
version = "0.1.0"
edition = "2024"

[lib]
name = "aeroplane_chess"
crate-type = ["lib", "cdylib"]

[dependencies]
bevy = "0.18.1"
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
getrandom = { version = "0.3.4", features = ["wasm_js"] }
console_error_panic_hook = "0.1.7"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.118"
web-sys = { version = "0.3.95", features = [
    "Document",
    "Element",
    "HtmlAudioElement",
    "HtmlElement",
    "HtmlMediaElement",
    "Location",
    "Window",
] }
